### ISSUE TITLE
Build fails under Ubuntu 21/Gcc 9.4

### ISSUE THREAD

**Issue by juanma1980** [msharov/pam_autologin#1]
Hi, i've been trying to compile the project under Ubuntu 21 with GCC 9.4
The compiler complains about the maybe_unused args:

autologin.c:287:57: error: expected expression before ‘[’ token
  287 | int pam_sm_authenticate (pam_handle_t* pamh, int flags [[maybe_unused]], int argc, const char** argv)

The project builds ok with GCC 11.

Also there's another problem with configure as Ubuntu (and perhaps Debian) doesn't ship a pam.pc for pkg-config so the dependency check fails. 

For this last problem I'll do a pull request that adds a parameter --no-pam-pkg for the configure process in order to avoid the check. Also I can do another PR with the debian folder for packaging under ubuntu/debian that includes a patch (with quilt) for removing the [[maybe_unused]], if you're interested.

Cheers.

**Comment by msharov** [comment]
Distribution specific packaging code is not and should not be part of the project. Packages usually have their own source repository somewhere, such as https://aur.archlinux.org/packages/pam_autologin for Arch.

**Comment by juanma1980** [comment]
With last commit builds OK. Thanks!

**Comment by msharov** [comment]
Commit ffd5fc8aaafe7f71e82397d5b1303b6c86640491: when pkg-config is misconfigured, ignore pkg-config and use fallback settings.
